apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: barmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.9.1
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: barmate
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: zookeeper
---
# ---------------- Kafka Brokers ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-0
  namespace: barmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-0
  template:
    metadata:
      labels:
        app: kafka-broker-0
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.9.1
          ports:
            - containerPort: 29092
            - containerPort: 30092
          env:
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:30092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker-0:29092,PLAINTEXT_HOST://localhost:30092"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "1"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_NUM_PARTITIONS
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-0
  namespace: barmate
spec:
  type: NodePort
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: external 
      port: 30092
      targetPort: 30092
      nodePort: 30092
  selector:
    app: kafka-broker-0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-1
  namespace: barmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.9.1
          ports:
            - containerPort: 29093
            - containerPort: 30093
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:30093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker-1:29093,PLAINTEXT_HOST://localhost:30093"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_NUM_PARTITIONS
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
  namespace: barmate
spec:
  type: NodePort
  ports:
    - name: internal
      port: 29093
      targetPort: 29093
    - name: external 
      port: 30093
      targetPort: 30093
      nodePort: 30093
  selector:
    app: kafka-broker-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-2
  namespace: barmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-2
  template:
    metadata:
      labels:
        app: kafka-broker-2
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.9.1
          ports:
            - containerPort: 29094
            - containerPort: 30094
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:30094"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker-2:29094,PLAINTEXT_HOST://localhost:30094"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_NUM_PARTITIONS
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-2
  namespace: barmate
spec:
  type: NodePort
  ports:
    - name: internal
      port: 29094
      targetPort: 29094
    - name: external 
      port: 30094
      targetPort: 30094
      nodePort: 30094
  selector:
    app: kafka-broker-2
---
# ---------------- Schema Registry ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-schema-registry
  namespace: barmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-schema-registry
  template:
    metadata:
      labels:
        app: kafka-schema-registry
    spec:
      containers:
        - name: kafka-schema-registry
          image: confluentinc/cp-schema-registry:7.9.1
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "kafka-schema-registry"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "kafka-broker-0:29092,kafka-broker-1:29093,kafka-broker-2:29094"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry
  namespace: barmate
spec:
  type: NodePort
  ports:
    - port: 8081
      name: http
      targetPort: 8081
      nodePort: 30081
  selector:
    app: kafka-schema-registry
---
# ---------------- Kafka Connect ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: barmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect-base:7.9.1
          ports:
            - containerPort: 8083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "kafka-broker-0:29092,kafka-broker-1:29093,kafka-broker-2:29094"
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_GROUP_ID
              value: "kafka-connect"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "_connect-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "_connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "_connect-status"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.storage.StringConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "io.confluent.connect.avro.AvroConverter"
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
              value: "http://schema-registry:8081"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: "kafka-connect"
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: barmate
spec:
  ports:
    - port: 8083
      name: http
  selector:
    app: kafka-connect
---
# ---------------- CLI Tools ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cli-tools
  namespace: barmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cli-tools
  template:
    metadata:
      labels:
        app: kafka-cli-tools
    spec:
      containers:
        - name: cli-tools
          image: confluentinc/cp-kafka:6.1.1
          command: ["sleep", "infinity"]
---
# ---------------- Kafka UI ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: barmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8099
          env:
            - name: SERVER_PORT
              value: "8099"
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-broker-0:29092,kafka-broker-1:29093,kafka-broker-2:29094"
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: "zookeeper:2181"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: barmate
spec:
  type: NodePort
  ports:
    - name: http
      port: 8099
      targetPort: 8099
      nodePort: 30099
  selector:
    app: kafka-ui